name: Hello GitHub Actions

on: [push]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "Hello, GitHub Actions!"
